name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 23 * * *'  # 2 a.m. EET is 0 a.m. UTC

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci --force

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      - name: Set up environment variables
        run: |
          echo "APP_URL=$(cat .env | grep APP_URL | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "ROLE_ADMIN=$(cat .env | grep ROLE_ADMIN | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "ROLE_READ_ONLY=$(cat .env | grep ROLE_READ_ONLY | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "ROLE_CUSTOMER_ADMIN=$(cat .env | grep ROLE_CUSTOMER_ADMIN | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "USER_PASSWORD=$(cat .env | grep USER_PASSWORD | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30